name: ui_background_task_example
description: Demonstrates how to use the ui_background_task plugin.
publish_to: "none"

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter
  ui_background_task:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
